import { StyleSheet } from 'react-native';
import { fonts } from '../../../../constants/fonts';

export const payUpfrontStyles = StyleSheet.create({
  safe: {
    flex: 1,
  },
  scroll: {
    paddingHorizontal: 20,
    paddingBottom: 32,
    paddingTop: 4,
  },
  heroCard: {
    borderRadius: 24,
    borderWidth: 1,
    padding: 22,
    marginBottom: 20,
    alignItems: 'center',
  },
  heroIcon: {
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  heroTitle: {
    fontFamily: fonts.PoppinsBold,
    fontSize: 20,
    lineHeight: 26,
    textAlign: 'center',
  },
  heroReceipt: {
    fontFamily: fonts.PoppinsRegular,
    fontSize: 13,
    marginTop: 4,
  },
  heroAmount: {
    fontFamily: fonts.PoppinsBold,
    fontSize: 28,
    marginTop: 10,
  },
  heroHint: {
    fontFamily: fonts.PoppinsRegular,
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
    marginTop: 14,
  },
  trialBanner: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    marginBottom: 16,
    gap: 6,
  },
  trialBannerTitle: {
    fontFamily: fonts.PoppinsSemiBold,
    fontSize: 14,
  },
  trialBannerText: {
    fontFamily: fonts.PoppinsRegular,
    fontSize: 13,
    lineHeight: 19,
  },
  refreshRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: 12,
    gap: 6,
  },
  refreshText: {
    fontFamily: fonts.PoppinsSemiBold,
    fontSize: 13,
  },
  detailCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    marginBottom: 20,
    gap: 12,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  detailLabel: {
    fontFamily: fonts.PoppinsRegular,
    fontSize: 13,
    flex: 1,
  },
  detailValue: {
    fontFamily: fonts.PoppinsSemiBold,
    fontSize: 13,
    flex: 1.2,
    textAlign: 'right',
  },
  payNowButton: {
    height: 52,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  payNowButtonText: {
    fontFamily: fonts.PoppinsBold,
    fontSize: 15,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  stateTitle: {
    fontFamily: fonts.PoppinsSemiBold,
    fontSize: 17,
    textAlign: 'center',
    marginTop: 12,
  },
  stateDesc: {
    fontFamily: fonts.PoppinsRegular,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 21,
    marginTop: 8,
    marginBottom: 16,
  },
  retryButton: {
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  retryButtonText: {
    fontFamily: fonts.PoppinsSemiBold,
    fontSize: 14,
  },
  uploadSectionLabel: {
    fontFamily: fonts.PoppinsSemiBold,
    fontSize: 12,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 12,
    marginLeft: 4,
  },
  uploadCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    marginBottom: 24,
  },
  uploadPlaceholder: {
    borderRadius: 16,
    paddingVertical: 32,
    paddingHorizontal: 20,
    alignItems: 'center',
    gap: 8,
  },
  uploadPlaceholderTitle: {
    fontFamily: fonts.PoppinsSemiBold,
    fontSize: 15,
  },
  uploadPlaceholderDesc: {
    fontFamily: fonts.PoppinsRegular,
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
  },
  previewWrap: {
    gap: 12,
    marginBottom: 16,
  },
  previewImage: {
    width: '100%',
    height: 220,
    borderRadius: 16,
    backgroundColor: '#e2e8f0',
  },
  removeImageBtn: {
    alignSelf: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  removeImageText: {
    fontFamily: fonts.PoppinsSemiBold,
    fontSize: 12,
    color: '#fff',
  },
  uploadActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  uploadActionBtn: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  uploadActionText: {
    fontFamily: fonts.PoppinsSemiBold,
    fontSize: 13,
  },
  submitButton: {
    height: 56,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 12,
  },
  submitButtonText: {
    fontFamily: fonts.PoppinsBold,
    fontSize: 15,
    letterSpacing: 0.5,
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  loadingText: {
    fontFamily: fonts.PoppinsMedium,
    fontSize: 14,
    marginTop: 14,
    letterSpacing: 0.5,
  },
});
